services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-agendamento:latest
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: agendamento_consultas

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: api-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: agendamento_consultas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agendamento_consultas"]
      interval: 5s
      timeout: 5s
      retries: 5
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN:?LOCALSTACK_AUTH_TOKEN não configurado}
      DEBUG: "0"
      PERSISTENCE: "1"

    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  localstack_data: